### ISSUE TITLE
Quick filter

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#1121]
When setting new advanced filters, the number of the added filters should be seen:
**Advanced (2)**
![image](https://user-images.githubusercontent.com/48472405/69145566-99553a00-0ad6-11ea-9186-e76d9b983aba.png)

@omrihecht @shmulikalbo

**Comment by raananmorag** [comment]
<img width="743" alt="Screen Shot 2019-11-19 at 14 14 47" src="https://user-images.githubusercontent.com/48472405/69145817-2e583300-0ad7-11ea-9d16-a5bd13d793e7.png">

The 'Condition-dropdown' should keep its width always.

**Comment by shmulikalbo** [comment]
Also lets add the first filter open in empty state, I got few feedback it looks odd when there is only a button and I agree.
It should appear with "None" as a placeholder text, currently once I choose it it doesn't  show.
![image](https://user-images.githubusercontent.com/49681330/72678187-3834ed00-3aac-11ea-9dff-1f2516e6f1cb.png)

**Comment by omrihecht** [comment]
@shmulikalbo , it cannot start with none selected, the second field is dependent on a value in the first field, and the third is dependent on the second.
atm we have a bug when selecting none in the first field, i am removing the none option there
do you want to show one open filter with the first field selected?

**Comment by shmulikalbo** [comment]
Ya show one filter open. Sent you a video on Slack. Currently it's selected by default but if I change the value from First name to Email and coming back to First name second field stay empty, as I want it to open as a default

.

**Comment by galloween** [comment]
@omrihecht closing this?

**Comment by omrihecht** [comment]
not yet

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/74099971-060a2e80-4b32-11ea-96bd-51956df7ad68.png)

Few text changes for this dialog - 
@doroncy @shmulikalbo
