### ISSUE TITLE
Number ticker

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#1193]
Add number ticker to input element
conditions to display:
- input element should be of type number
- add new Input (i think interface) that has
```
{
tickValue
maxValue
minValue
}
```

this is the design:
https://hibob.invisionapp.com/d/main#/console/14664741/304942710/preview
![image](https://user-images.githubusercontent.com/24462119/70890008-a2113100-1fec-11ea-95dc-cc4eae0251f2.png)

**Comment by galloween** [comment]
I want to elaborate:

- we already have min max value inputs implemented - you can see it in the storybook - if you enter a value that is less then min or bigger then max, it will be changed to min or max respectively
- so we need just 1 additional input for the step the number will be increased/decreased with - lets call it **step** (same as the native html attribute)

#### Important note on the form elements architecture:
 - the input component functionality is split between **BaseInputElement** (base-input-element.ts), which is shared with the textarea component and the **InputComponent** component itself (input.component.ts). 
- The input component (and more precisely, the BaseInputElement) also extends **BaseFormElement** which contains logic common to all form elements.

To keep with this structure, I would approach this task in the following way:
- add **step** input of type number to BaseInputElement
- add 2 buttons to input.component.html. for the buttons to have chevron icons, you can add the following classes: 'b-icon b-icon-chevron-up b-icon-large b-icon-normal has-hover' for the + and 'b-icon b-icon-chevron-down b-icon-large b-icon-normal has-hover' for the -. Style accordingly (borders, etc). buttons should only show if type is number.
- add handler methods to BaseInputElement. what you need to do is increment the input DOM element value itself (then this change will be caught by existing onInputChange method and processed).
- to reach the input DOM element value, you can use **this.input.nativeElement.value'
