### ISSUE TITLE
Directory: Action icons

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#1194]
<img width="1306" alt="Screen Shot 2019-12-16 at 10 53 25" src="https://user-images.githubusercontent.com/48472405/70892823-8872e800-1ff2-11ea-80e4-3f41fcae91eb.png">

@omrihecht 
Action icons need to be above the grid.
While one or more checkbox is selected - Hide the buttons.

cc @shmulikalbo

**Comment by shmulikalbo** [comment]
@omrihecht thanks for the quick fix! 
Small ux fix needed as currently the icons stays the same when user click one of the checkbox on the left. It can confuse as the one he just selected can be downloaded or saved. We need to hide all icons once one of the rows is selected so it's super clear once I select one of the rows Action button is activated and these are the actions you can select.

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/72734836-49acf080-3ba3-11ea-9a3b-ba5c651d58d6.png)

Pressing the main checkbox:
 - When one or more row is selected - **Clear all**
- When none is selected - **Select all**

+Also :
add counter( "**Selected: 2**" )when selecting rows, next to the Action button

@omrihecht 
cc @shmulikalbo
