### ISSUE TITLE
Company Registration Dialog

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#1213]
![image](https://user-images.githubusercontent.com/48472405/71182592-021f0600-227f-11ea-85b2-4e74c4cf5f5d.png)
 

- steps -circles should be 8px size and 8px between each.
![image](https://user-images.githubusercontent.com/48472405/71181908-be77cc80-227d-11ea-86f9-76e8b1d6b872.png)

 - Add a transition between steps - a small fading-animation  - slide to the left
 - Add a transition between 'Hi' gif to 'Success' gif - a slide left animation (masked inside the right section)

@omrihecht

**Comment by raananmorag** [comment]
Use these gifs:
[Archive.zip](https://github.com/hibobio/bob-style/files/3984278/Archive.zip)

![Hi](https://user-images.githubusercontent.com/48472405/71185773-c1c28680-2284-11ea-9061-3b135b8cfa74.gif)
![Success](https://user-images.githubusercontent.com/48472405/71185774-c25b1d00-2284-11ea-9b22-d15a2a0b92b7.gif)

**Comment by omrihecht** [comment]
done
