### ISSUE TITLE
Grid - remove single column

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#1253]
<img width="1224" alt="Screen Shot 2019-12-25 at 14 13 42" src="https://user-images.githubusercontent.com/48472405/71445239-d4273f00-2720-11ea-95ee-a640053a30aa.png">

Use our (X) icon for this action.
![image](https://user-images.githubusercontent.com/48472405/71445351-94ad2280-2721-11ea-827a-d2337ad437f8.png)

@omrihecht

**Comment by omrihecht** [comment]
done
