### ISSUE TITLE
Multi select drop down

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#134]
[multi select](https://hibobio.github.io/bob-style/?selectedKind=Form%20Elements&selectedStory=Multi%20select&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel):
cc: @levben @Rotemfischbob

**Comment by ishaiborovoy** [comment]
Handle the errorMessage, show it

**Comment by ishaiborovoy** [comment]
disabled is not working
