### ISSUE TITLE
Data Table

### ISSUE THREAD

**Issue by doroncy** [hibobio/bob-style#179]
##### Table Grid API
- [x] Columns Config (meta data on column)
- [x] Data source (need to support deep JSON)
- [x] Multi select 

##### Table Grid requirements
- [x] Custom components (make sure high performance)
- [x] Cell formaters (show currency, date) ? maybe no need
- [x] Pinned columns
- [x] Sorting (custom comperator)
- [x] Resize columns
- [x] Column ordering
- [ ] Remove columns
- [x] Overtall Performance 
- [x] Select all
- [ ] Add truncate tooltip logic

##### need to talk to ben
- [ ] Column picker

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/58171447-b1224180-7c9e-11e9-8913-632973e8b6ce.png)
- table's title row should be white-background, not gray.
- and the category's text should be medium font-weight.
@doroncy
