### ISSUE TITLE
lists

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#230]
- [x] single list
- [x] single select
- [x] multi list
- [x] multi selelct

todo:
- [x] test keyboard event
- [x] test search focus
- [x] open keyboard subscription on element focus and unsubscribe on blur

**Comment by raananmorag** [comment]
Multi-select with switch toggle was added to the design system.
@omrihecht 

![Screen Shot 2019-05-06 at 12 49 41](https://user-images.githubusercontent.com/48472405/57218215-701f0180-6ffd-11e9-9781-bb966332987a.png)



Invision:
https://hibob.invisionapp.com/share/G2RV14C4TKD

**Comment by raananmorag** [comment]
Multi-select dropdown should be collapsed by default.
![image](https://user-images.githubusercontent.com/48472405/57602074-d5777300-7566-11e9-93a1-9fbcfdc568d5.png)
@omrihecht

**Comment by omrihecht** [comment]
@raananmorag , are you referring to this component or to every multi list?

**Comment by raananmorag** [comment]
@omrihecht Every multi list..

**Comment by doroncy** [comment]
@raananmorag what should be the behavior when you search and clear search

**Comment by raananmorag** [comment]
**behavior**

**group of one**
- always open


**more than one group**
- starts closed
- search opens the relevant groups 
- clear search reset to close groups

**Comment by doroncy** [comment]
not in use, closing
