### ISSUE TITLE
quick filters

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#232]
https://hibob.invisionapp.com/d/main/#/console/14664741/335240048/inspect

**Comment by omrihecht** [comment]
@Rotemfischbob @levben , please provide design for this
this is the component:
https://hibobio.github.io/bob-style/?selectedKind=Navigation&selectedStory=Quick%20filters&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fnotes%2Fpanel

**Comment by raananmorag** [comment]
- [ ] change "more" to be a link button
- [ ] update reset icon
- [ ] label truncate
- [ ] label size (in quick filter scale should be 1)

**Comment by omrihecht** [comment]
moved here:
https://github.com/hibobio/bob-style/issues/595
