### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by doroncy** [hibobio/bob-style#37]
https://hibob.invisionapp.com/share/VSPRE3VARUP

**Comment by omrihecht** [comment]
[checkbox](https://hibobio.github.io/bob-style/?selectedKind=Form%20Elements&selectedStory=Checkbox&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel)
cc: @levben @Rotemfischbob

**Comment by ishaiborovoy** [comment]
Need to handle the `writeVlaue`, it's not getting it

**Comment by raananmorag** [comment]
https://hibob.invisionapp.com/share/AZS5YJLX8E4
checkbox style has been updated:
![image](https://user-images.githubusercontent.com/48472405/58235629-dfa92680-7d49-11e9-9e2a-2e9dbb1e8f5f.png)
@doroncy
