### ISSUE TITLE
link

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#405]
design:
https://hibob.invisionapp.com/d/main/#/console/14664741/339500511/preview
(under text links)

lets use interface that has the text and url

**Comment by omrihecht** [comment]
@tomeraronovsky shouldn't there be an input for color?
i don't remember what we discussed
![image](https://user-images.githubusercontent.com/24462119/56468351-d7508980-6433-11e9-8503-2f92f5f3f1f7.png)

**Comment by tomeraronovsky** [comment]
all link settings in the Link object
