### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#406]
https://hibob.invisionapp.com/d/main/#/console/14664741/358402970/preview

**Comment by omrihecht** [comment]
@tomeraronovsky , any progress?
cc: @raananmorag

**Comment by tomeraronovsky** [comment]
still need to add the animations

**Comment by raananmorag** [comment]
@tomeraronovsky 
![image](https://user-images.githubusercontent.com/48472405/59348646-4fdf1280-8d20-11e9-8d96-bf427d19b4be.png)

be noticed that the close icon color should be 'gray-600' (#9D9D9D).

**Comment by doroncy** [comment]
@tomeraronovsky are we done with this? do we add some open/close animation?

**Comment by doroncy** [comment]
@tomeraronovsky are we done with this? do we add some open/close animation?

**Comment by tomeraronovsky** [comment]
@doroncy No, still need to add the open close animation. by priority, I need to finish some feedback feature issues before getting back to the animation

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/62297811-8876af00-b47a-11e9-8a78-84462e622ed6.png)

When it is an **error** alert:
The alert needs to stay and not to disappear as other types of alerts.
(Only the user will close the error-alerts)
@tomeraronovsky @shmulikalbo
