### ISSUE TITLE
CallOut

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#407]
https://hibob.invisionapp.com/share/5WRL54PPQZX

dependecy:
panel position strategy

**Comment by omrihecht** [comment]
https://github.com/hibobio/bob-style/pull/422

**Comment by raananmorag** [comment]
@doroncy 
https://hibob.invisionapp.com/share/5WRL54PPQZX

Callout padding changed a little bit

**Comment by omrihecht** [comment]
callout panel is ready, let's separate employee summary to a separate issue, not related to bob-style
