### ISSUE TITLE
input field

### ISSUE THREAD

**Issue by doroncy** [hibobio/bob-style#41]
https://hibob.invisionapp.com/share/REPRE5ANQ56

all the input types should be in one element, just getting a different type parameter

**Comment by omrihecht** [comment]
[basic input element](https://hibobio.github.io/bob-style/?selectedKind=Form%20Elements&selectedStory=Input&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel)
cc: @Rotemfischbob @levben

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/57689111-99680f00-7647-11e9-861a-6ffa3b412b2e.png)
Input label and hint text shouldn't have the same text color:
**Label color:** #535353
**Hint color:** #9D9D9D

@omrihecht

**Comment by omrihecht** [comment]
@raananmorag , let's align the terminology:
label = address
placeholder = eg text field
hint = below the field (grey)
error = below the field (red)


atm i don't think we implemented placeholder, need to do that

**Comment by raananmorag** [comment]
@omrihecht 
Ok, then -
Label color: #535353
Placeholder color: #9D9D9D

**Comment by omrihecht** [comment]
but where have you seen a placeholder?

**Comment by raananmorag** [comment]
label = address
**placeholder = eg text field**

right?

**Comment by omrihecht** [comment]
exactly

**Comment by galloween** [comment]
there might be cases when there is no padding on the label / input - like in the tags/chips input https://hibob.invisionapp.com/d/main/#/console/14664741/363162463/preview
lets discuss when @omrihecht gets back and refactor as needed

**Comment by omrihecht** [comment]
done
