### ISSUE TITLE
overlay panel

### ISSUE THREAD

**Issue by doroncy** [hibobio/bob-style#43]
need to investigate the CDK overlay, this will be used in panels and dropdowns

**Comment by omrihecht** [comment]
[overlay panel](https://hibobio.github.io/bob-style/?selectedKind=Overlay&selectedStory=Panel&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel)
cc: @Rotemfischbob @levben

**Comment by omrihecht** [comment]
- [ ] add position strategy
- [ ] add basic position strategy input

**Comment by galloween** [comment]
done.
