### ISSUE TITLE
slider

### ISSUE THREAD

**Issue by doroncy** [hibobio/bob-style#44]
use the same style that you did for the goals

**Comment by omrihecht** [comment]
button size: 14px; shadow: 0 2px 5px shadowColor
on-hover: 16px; shadow: 0 2px 5px shadowColor

**Comment by omrihecht** [comment]
done

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/64608640-d06ee700-d3d3-11e9-924e-60cabe353a02.png)
@doroncy @omrihecht @shmulikalbo 
Progress bar (colored line) should get the same hight as the gray bar behind it. (8 px)
