### ISSUE TITLE
New Card type (employee card)

### ISSUE THREAD

**Issue by galloween** [hibobio/bob-style#456]
https://hibob.invisionapp.com/share/5GQD97YFCP9#/screens/359560684

![image](https://user-images.githubusercontent.com/2077754/56950190-8e888700-6b3d-11e9-9972-b0e50ea8b7e2.png)

**Comment by omrihecht** [comment]
this isn't the employee card, this is the one with the image

**Comment by galloween** [comment]
I attached the wrong screenshot :)
