### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by doroncy** [hibobio/bob-style#46]
same design as the current one, 
need some architecture work in order to use the mention service, lets talk about it

- [x] add quilljs (find d.ts for it)
- [x] editor with bold / italics / underline / link / font-size
- [ ] accept SelectGroupOption[] for mentions ?
- [x] links - add blot
- [ ] tests

**Comment by doroncy** [comment]
yes, there is an option in quill to have placeholder

**Comment by raananmorag** [comment]
@oriv @tomeraronovsky 
☝

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/66268811-d24c8e80-e849-11e9-997a-fab3ae9a8754.png)

Updated design.

Invision: https://hibob.invisionapp.com/d/main#/console/14664741/387331171/preview
@galloween @omrihecht @doroncy 

cc: @shmulikalbo
