### ISSUE TITLE
avatar badge

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#485]
The icons used for the badge are bad, not centerer and unaligned.
we need to replace them and then reposition in the avatar element.
![image](https://user-images.githubusercontent.com/24462119/57094277-d8799480-6d18-11e9-8266-2b39981eebbb.png)
![image](https://user-images.githubusercontent.com/24462119/57094333-fd6e0780-6d18-11e9-899e-a3c165a99ef4.png)

**Comment by omrihecht** [comment]
@danidin , please lmk that you've seen this

**Comment by galloween** [comment]
please keep me in the loop, im in charge of this component now

**Comment by raananmorag** [comment]
@galloween @doroncy 

https://hibob.invisionapp.com/share/DKRL544FN2U

 - avatars with badges updated

 - Large avatar label isn't correct on Storybook.
(Missing the department and site line)

![image](https://user-images.githubusercontent.com/48472405/58094354-29beca80-7bd9-11e9-8fdc-49dec3515325.png)

- Need the medium and large avatar to be with an optional status chip.

**Comment by raananmorag** [comment]
Also, there is a design for avatar-chip
![image](https://user-images.githubusercontent.com/48472405/58100917-4530d200-7be7-11e9-8d57-d604fc9c904c.png)

**Comment by galloween** [comment]
🐶
