### ISSUE TITLE
Typography 

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#495]
Typography style changed for "HEADING" - Need to change to  **14PX** instead of 16PX

Invision Link:
https://hibob.invisionapp.com/share/S7RL55TVUJM

![Screen Shot 2019-05-06 at 12 19 37](https://user-images.githubusercontent.com/48472405/57217035-34366d00-6ffa-11e9-9d95-d8199eabae2d.png)

**Comment by raananmorag** [comment]
@omrihecht

**Comment by omrihecht** [comment]
Thanks @raananmorag
