### ISSUE TITLE
Tabs Navigation

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#501]
Invision link: 
https://hibob.invisionapp.com/share/HTRV7R6YXGU

Tab Navigation design added to the design system.
 
@omrihecht @doroncy

**Comment by galloween** [comment]
assigning to myself

**Comment by raananmorag** [comment]
@galloween @omrihecht 
can the max-width be 100%, without the (-62px)?

**Comment by omrihecht** [comment]
@raananmorag , width of what? can you provide screenshot please?

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/59844855-8c37f180-9364-11e9-85ba-afe9f05524e8.png)
![image](https://user-images.githubusercontent.com/48472405/59844862-90fca580-9364-11e9-802f-0c5797c226f7.png)
@omrihecht

**Comment by omrihecht** [comment]
@galloween , @raananmorag , talk!
