### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#585]
Colours:
 - [x] idle: color-600
 - [x] hover: color-500
 - [x] active: color-700

Types
 - [x] Change tertiary to be like ghost (no hover and active)

Square button
 - [x] icon size should be 24

Components
 - [x] add link button

**Comment by raananmorag** [comment]
**Icon-buttons**

Some decisions we've made about Icon-buttons' color:
 - When the icon placed inside an input/table row, the color should be **gray-600**
![image](https://user-images.githubusercontent.com/48472405/58623683-34fbaf80-82d7-11e9-9588-0448e61cdf2a.png)


 - When the icon placed as a higher level action (download, save, etc.), the color should be **gray-700**
![image](https://user-images.githubusercontent.com/48472405/58628106-8f9a0900-82e1-11e9-9436-fb1b7de90ee3.png)
@omrihecht

**Comment by omrihecht** [comment]
@raananmorag , @shmulikalbo 
we need to come up with better logic for the components then where it is placed, we need to assume that the component "doesn't know" if it is being used inside high level action or bottom level action.
let's talk and decide on logic that can be applied

**Comment by omrihecht** [comment]
@raananmorag , i'm moving the table bar subject to tables, it's not part of icons.

**Comment by raananmorag** [comment]
Here's an example of how action buttons can be placed above the grid, with the "total" strip area:

![image](https://user-images.githubusercontent.com/48472405/58759023-6caf6500-852c-11e9-92da-c88f1ac59f66.png)

**Comment by omrihecht** [comment]
done

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/60430704-9c728b00-9c06-11e9-90dd-bce6563e2fec.png)
Secondary button has been updated
Invision: https://hibob.invisionapp.com/share/PQPRE4AUFXA

 
@omrihecht @shmulikalbo

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/60793556-99c8e600-a170-11e9-9d95-2494238cce3b.png)
 - Remove border
 - remove all shadows (in & out)


 **Secondary button**
 - Idle: '#e2e2e2' (We dont use this color at the moment. can we add it as gray-400? or just change the 'gray-300' to be darker?
 - Hover: '#e9e9e9'
 - Pressed - '#d2d2d2'


@omrihecht @shmulikalbo
