### ISSUE TITLE
Chips: remove colors

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#586]
Colour list should include
 - attention - rename to warning
 - success
 - tag
 - warning - rename to error
 - info
all the rest should be removed 
before renaming and removing we need to check nothing breaks

---
 - add a little padding to remove tag close button left and right

**Comment by raananmorag** [comment]
@omrihecht @shmulikalbo 
Attention color should be '#F0AD00'.
** Tag pressed state color should stay '#FF962B' **

**Comment by omrihecht** [comment]
done
