### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#592]
action buttons:
 - changes size to medium
 - remove 100% percent width logic

close button:
 - change icon to lighter type of X
 - use ghost button type (square)
 - margin from corner: 5px

**Comment by raananmorag** [comment]
- The close button should be 'gray-600'.

@omrihecht 
![image](https://user-images.githubusercontent.com/48472405/59766831-ae206e00-92a9-11e9-9e1b-402128b825ee.png)

**Comment by omrihecht** [comment]
Np

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/59998477-31eea780-9668-11e9-85ed-ba6f0331f042.png)
We really need the option to have:
- only the **x** button without the **close** button, 
- and the option to have the **close** button without the **x** button.

@shmulikalbo @omrihecht

**Comment by omrihecht** [comment]
@raananmorag , @shmulikalbo , still don't understand the behaviour, why not always remove one of them (remove the x?)
cc: @doroncy

**Comment by shmulikalbo** [comment]
Here are few examples why we need to keep both options and use them currently in the product :

![image](https://user-images.githubusercontent.com/49681330/60020556-ef918e80-9698-11e9-943b-f3b86ef7446e.png)

![image](https://user-images.githubusercontent.com/49681330/60020584-f9b38d00-9698-11e9-9ee3-4cc875d5bd06.png)

![image](https://user-images.githubusercontent.com/49681330/60020595-00da9b00-9699-11e9-8e19-c59dad161c35.png)
