### ISSUE TITLE
Collapsible

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#593]
- chevron direction: closed: right, open: down
 - remove chevron animation (align behaviour with multi group lists)

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/60188120-72e8e680-9837-11e9-9542-5288928ced6b.png)
We need this type of collapsible.
 - Triggered by toggle
 - No icon before the label
 - the expand container's background has opacity, so it can be placed on white/gray bg.


https://hibob.invisionapp.com/share/NTSPCERVUJ8

@galloween @omrihecht @doroncy @shmulikalbo

**Comment by omrihecht** [comment]
@raananmorag , @shmulikalbo , do we need 3 types of collapsibles?
we have 3 options before we have 1 usecase.
maybe we should drop one of the 2 we have today, wdyt?

**Comment by shmulikalbo** [comment]
lets meet and finalize this issue

**Comment by raananmorag** [comment]
Updated 
https://hibob.invisionapp.com/share/NTSPCERVUJ8

**Comment by omrihecht** [comment]
Thanks
