### ISSUE TITLE
Quick filters

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#595]
- [x] label should always be on top (fixed by input fix)
 - [x] label colour should be the same as now (need to overwrite select label colour)
 - [x] add empty value placeholder
 - [x] add reset button

story book
 - [x] change more to ghost button

cc: @raananmorag

**Comment by raananmorag** [comment]
<img width="740" alt="Screen Shot 2019-06-17 at 10 24 16" src="https://user-images.githubusercontent.com/48472405/59585858-20e2eb00-90ea-11e9-933f-8866ead8f64a.png">

On mouse hover - Cursor should change to the hand cursor. 
![image](https://user-images.githubusercontent.com/48472405/59586136-dd3cb100-90ea-11e9-9d06-ee92d4671b6d.png)

Now the cursor is changing only when hovering the input field, not the drop-down icon.
@omrihecht
