### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#600]
Invision:
https://hibob.invisionapp.com/share/5PS96ASH6TX

 - A "Total/selected-counter" should be placed above the table.
![image](https://user-images.githubusercontent.com/48472405/58557384-f1496d00-8226-11e9-9a06-53bf4ed10a0c.png)
![image](https://user-images.githubusercontent.com/48472405/58557447-1a69fd80-8227-11e9-81ba-753b471d0ce7.png)

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/58617961-1642ec00-82ca-11e9-83e7-f7b7216f7240.png)

Also, this line above the table will allow us to place relevant actions to the grid. 
@omrihecht

**Comment by raananmorag** [comment]
<img width="891" alt="Screen Shot 2019-05-30 at 15 53 08" src="https://user-images.githubusercontent.com/48472405/58634200-4fdc1d00-82f3-11e9-9b8f-0bd46a66819a.png">

Categories should be left aligned to the Separators lines.
 like this:
![image](https://user-images.githubusercontent.com/48472405/58634289-a0537a80-82f3-11e9-91f0-bfcca966627c.png)

**Comment by doroncy** [comment]
duplicate #610
