### ISSUE TITLE
Data table

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#610]
Add data table header that has text slot and ng-content slot, 
@raananmorag , please update invision link here

**Comment by raananmorag** [comment]
Invision:
https://hibob.invisionapp.com/share/5PS96ASH6TX

**Comment by raananmorag** [comment]
<img width="751" alt="Screen Shot 2019-07-01 at 10 05 52" src="https://user-images.githubusercontent.com/48472405/60417003-f44dc980-9be7-11e9-877b-59775910a3fc.png">

 These icons should be 'gray-600'
@omrihecht
