### ISSUE TITLE
Side menu

### ISSUE THREAD

**Issue by omrihecht** [hibobio/bob-style#615]
Update side menu design
@raananmorag , please add invision link here.

**Comment by raananmorag** [comment]
Invision:
https://hibob.invisionapp.com/share/XRSBJ1W4TYF

**Comment by omrihecht** [comment]
background-color: transparent

**Comment by danazelniker** [comment]
@raananmorag Do we have special empty state? or is it just an empty list?

**Comment by danazelniker** [comment]
@raananmorag What is the icon next to the download? is it suppose to be create folder? it's not so clear.

**Comment by danazelniker** [comment]
@benbaler I see this one is not done.
@raananmorag I had two questions... see above.

**Comment by raananmorag** [comment]
@danazelniker 
![image](https://user-images.githubusercontent.com/48472405/59248134-35c30880-8c2a-11e9-8a6d-e78b403befe6.png)
this is the 'Add new folder icon'. the other one was just a placeholder of an action icon above the list.

**Comment by raananmorag** [comment]
@benbaler @danazelniker 
I've updated the empty states:
https://hibob.invisionapp.com/share/XRSBJ1W4TYF

![image](https://user-images.githubusercontent.com/48472405/59274500-22805f00-8c63-11e9-8a13-0d752831ab95.png)

![image](https://user-images.githubusercontent.com/48472405/59274509-27451300-8c63-11e9-8d66-10ceab592d42.png)

**Comment by omrihecht** [comment]
@benbaler , is this done? if yes please close issue

**Comment by raananmorag** [comment]
@omrihecht @benbaler 
According to whats on storybook, it's not done yet.
![image](https://user-images.githubusercontent.com/48472405/59565826-96a27480-9060-11e9-81b0-ff9eab7f4532.png)

- selected icon should be white (the folder icon).
- looks like the icon is smaller than 24px (?).

**Comment by doroncy** [comment]
@benbaler close this when done
