### ISSUE TITLE
Form-elements refactor

### ISSUE THREAD

**Issue by galloween** [hibobio/bob-style#639]
**Changes**

 -

**Comment by omrihecht** [comment]
### HIBOB-WEB-CLIENT

------

**Not used**

- b-social
- b-autocomplete*
- *b-quick-filter*

------

**Form Generator**

- [ ] b-input
- [ ] **b-checkbox**
- [ ] **b-chip-input**
- [ ] b-datepicker
- [ ] b-multi-select
- [ ] b-single-select
- [ ] <u>b-radio-button</u>
- [ ] b-textarea
- [ ] b-rich-text-editor

------

**Spouse.component**

- [ ] b-input
- [ ] b-datepicker
- [ ] b-single-select

------

**People.component**

- [ ] b-input			does not use enums
- [ ] <u>b-radio-button</u>     does not use enums

------

**Address.component**

- [ ] b-input

------

**Employees.component**

- [ ] *b-search*

------

**Step-description.component**

- [ ] b-input
- [ ] b-textarea

------

**Step-introduction.component**

- [ ] b-input 		does not use enums
- [ ] b-rich-text-editor     does not use enums

------

**Step-welcome-email.component**

- [ ] b-input

------

**Media-uploader.component**

- [ ] b-input  		does not use enums

------

**Step-documents**

- [ ] b-multi-select

------

**Employee-ref-multi-select.component**

- [ ] b-multi-select
- [ ] b-single-select

------

**Currency-value-select.component**

- [ ] b-split-input

  

------

------



### HIBOB-WEB

------

**Not used**

- b-input
- b-checkbox
- b-radio-button
- b-social
- b-datepicker
- b-rich-text-editor
- b-split-input
- *b-autocomplete*

------

**People-feedback.component**

- [ ] *b-search*

- [ ] *b-quick-filter*

------

**Approval-requests.component**

- [ ] *b-quick-filter*
- [ ] *b-search*

------

**Update-tags-dialog.component**

- [ ] b-chip-input

------

**Sharing-settings-folder-dialog.component**

- [ ] b-multi-select

------

**Survey-result-open-question.component**

- [ ] b-single-select

------

**RejectRequestDialog.component**

- [ ] b-textarea

  



------

------



### SURVEYS-CLIENT

------

**Not used**

- b-social
- b-input
- b-checkbox
- b-chip-input
- b-datepicker
- b-multi-select
- b-single-select
- b-radio-button
- b-textarea
- b-split-input
- *b-autocomplete*
- *b-quick-filter*
- *b-search*

------

**OpenQuestion.component**

- [ ] b-rich-text-editor       does not use enum    uses focused event

------

**Question-title-edit.component**

- [ ] B-rich-text-editor       does not use enum

**Comment by omrihecht** [comment]
done
