### ISSUE TITLE
Chip-Input - Enhance behavior

### ISSUE THREAD

**Issue by Maornakash** [hibobio/bob-style#642]
Today in bob-style 2.0, the chip-input component is inserting only upon clicking 'Enter'
https://hibobio.github.io/bob-style/?path=/story/components-buttons-indicators-chips--chip-input

same behavior as "Enter", should be also upon 'Focus-out' from the field, or clicking 'Tab'.
This is standard behavior. (See reference in Gmail)

**Comment by omrihecht** [comment]
cc: @galloween , when you have time

**Comment by galloween** [comment]
implemented in new version. also it adds on comma press

**Comment by omrihecht** [comment]
done
