### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#697]
![image](https://user-images.githubusercontent.com/48472405/60181893-ea187d80-982b-11e9-8324-8798e7a32ac4.png)
Wizard (aka breadcrumbs) should be like this by default (Not showing each step's label - only the current step).
@shmulikalbo @omrihecht

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/60261778-60c58180-98e5-11e9-9f40-e125cba7c710.png)
Design has been updated.
 - circles are bigger (24px)
 - font is bigger
 - arrow icon is bigger (20px)

https://hibob.invisionapp.com/share/PMSPZW3BDJ5

@omrihecht 
@shmulikalbo

**Comment by omrihecht** [comment]
done
