### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by raananmorag** [hibobio/bob-style#778]
Invision: https://hibob.invisionapp.com/share/5SSUXNJJCKD
@omrihecht @doroncy @shmulikalbo

**Comment by raananmorag** [comment]
![image](https://user-images.githubusercontent.com/48472405/63676396-85f64380-c7f3-11e9-9682-8e2afad15c21.png)
Icon size should be 20px not 16px.
@doroncy

**Comment by galloween** [comment]
whoever uses the cards can put any size icon there. I updated the storybook examples with bigger icons, though.
